apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nats.fullname" . }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "nats.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nats.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nats.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: nats
          image: "ghcr.io/nats-io/nats:2.10.0-alpine"
          args: ["-js", "-sd", "/data/jetstream"]
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 8222
              name: monitor
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: nats-data
              mountPath: /data/jetstream
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: nats-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nats.fullname" . }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 4222
      targetPort: 4222
      name: client
    - port: 8222
      targetPort: 8222
      name: monitor
  selector:
    app.kubernetes.io/name: {{ include "nats.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
