apiVersion: aquasecurity.github.io/v1alpha1
kind: ExposedSecretReport
metadata:
  name: kcm-cluster-secret-detection-summary
  namespace: trivy-system
  labels:
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/part-of: kcm-security-platform
spec:
  updateTimestamp: "2026-07-29T18:00:00Z"
  summary:
    criticalCount: 0
    highCount: 0
    mediumCount: 0
    lowCount: 0
  secrets: []
