apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kcm-secrets-external
  namespace: kcm-prod
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: kcm-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: /kcm/prod/DATABASE_URL
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: /kcm/prod/NEXTAUTH_SECRET
    - secretKey: CLOUDINARY_API_SECRET
      remoteRef:
        key: /kcm/prod/CLOUDINARY_API_SECRET
    - secretKey: FIREBASE_PRIVATE_KEY
      remoteRef:
        key: /kcm/prod/FIREBASE_PRIVATE_KEY
