# Helm values file for KCM Logging Platform Umbrella Chart

global:
  environment: production
  clusterName: kcm-k8s-prod

loki:
  deploymentMode: SingleBinary

alloy:
  alloy:
    configMap:
      create: true
      name: alloy-config
