apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    # Roles definition
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, *, *, allow
    p, role:org-admin, logs, get, */*, allow
    p, role:org-admin, exec, create, */*, allow

    p, role:devops, applications, *, */*, allow
    p, role:devops, clusters, get, *, allow
    p, role:devops, repositories, get, *, allow
    p, role:devops, logs, get, */*, allow
    p, role:devops, exec, create, */*, allow

    p, role:developer, applications, get, */*, allow
    p, role:developer, applications, sync, frontend/*, allow
    p, role:developer, applications, sync, backend/*, allow
    p, role:developer, logs, get, frontend/*, allow
    p, role:developer, logs, get, backend/*, allow

    # Group Mappings
    g, "kcm:platform-admins", role:org-admin
    g, "kcm:devops-engineers", role:devops
    g, "kcm:developers", role:developer
