apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # General Configuration
  url: https://argocd.kcmchurch.org
  admin.enabled: "true"

  # Resource Customizations
  resource.customifications.health.argoproj.io_Rollout: |
    hs = {}
    if obj.status ~= nil then
      if obj.status.phase ~= nil then
        if obj.status.phase == "Healthy" or obj.status.phase == "Completed" then
          hs.status = "Healthy"
          hs.message = obj.status.phase
          return hs
        elseif obj.status.phase == "Paused" then
          hs.status = "Suspended"
          hs.message = "Rollout is paused"
          return hs
        elseif obj.status.phase == "Progressing" then
          hs.status = "Progressing"
          hs.message = "Rollout in progress"
          return hs
        elseif obj.status.phase == "Degraded" then
          hs.status = "Degraded"
          hs.message = "Rollout degraded"
          return hs
        end
      end
    end
    hs.status = "Progressing"
    hs.message = "Waiting for rollout status"
    return hs

  resource.exclusions: |
    - apiGroups:
      - cilium.io
      kinds:
      - CiliumNode
      clusters:
      - "*"

  # Resource Tracking Strategy
  application.resourceTrackingMethod: annotation

  # Git Repositories Configuration
  repositories: |
    - url: https://github.com/bunnyvalluri/kcm-church-infra.git
      type: git
      name: kcm-church-infra
    - url: https://github.com/bunnyvalluri/kcm-church-app.git
      type: git
      name: kcm-church-app

