apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-storage-pvc
  namespace: monitoring
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: tracing
    app.kubernetes.io/part-of: kcm-church
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single-replica
  resources:
    requests:
      storage: 50Gi
