apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-processing-pvc
  namespace: default
  labels:
    app.kubernetes.io/name: media-processor
    app.kubernetes.io/component: media-processing
    app.kubernetes.io/part-of: kcm-church
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-fast
  resources:
    requests:
      storage: 250Gi
