apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: cache
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: kcm-church
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-redis
  resources:
    requests:
      storage: 20Gi
