apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upload-services-pvc
  namespace: default
  labels:
    app.kubernetes.io/name: upload-service
    app.kubernetes.io/component: uploads
    app.kubernetes.io/part-of: kcm-church
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-replicated
  resources:
    requests:
      storage: 100Gi
