apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-loki
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"
  dataLocality: "best-effort"
  replicaAutoBalance: "least-effort"
  unmapMarkSnapChainRemoved: "ignored"
