apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kcm-observability-stack
  namespace: argocd
  labels:
    environment: prod
    component: observability
    app.kubernetes.io/part-of: kcm-platform
spec:
  project: monitoring
  source:
    repoURL: 'https://github.com/bunnyvalluri/church-.git'
    targetRevision: HEAD
    path: monitoring/kubernetes
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
