apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kcm-root-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: 'https://github.com/bunnyvalluri/kcm-church-infra.git'
    targetRevision: HEAD
    path: kcm-church-infra/argocd/applications
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
