apiVersion: v1
kind: Secret
metadata:
  name: kcm-secrets
  namespace: kcm-system
  labels:
    app.kubernetes.io/name: kcm-portal
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://<DB_USER>:<DB_PASSWORD>@postgres-db.kcm-system.svc.cluster.local:5432/kcm_db?sslmode=disable"
  NEXTAUTH_SECRET: "<GENERATE_32_BYTE_HEX_OR_BASE64_SECRET>"
  NEXTAUTH_URL: "http://kcm-portal.local"
  CLOUDINARY_CLOUD_NAME: "<CLOUDINARY_NAME>"
  CLOUDINARY_API_KEY: "<CLOUDINARY_KEY>"
  CLOUDINARY_API_SECRET: "<CLOUDINARY_SECRET>"
  FIREBASE_PROJECT_ID: "<FIREBASE_PROJECT_ID>"
  FIREBASE_CLIENT_EMAIL: "<FIREBASE_CLIENT_EMAIL>"
  FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\n<FIREBASE_PRIVATE_KEY_DATA>\n-----END PRIVATE KEY-----\n"
