apiVersion: v1
kind: Secret
metadata:
  name: kcm-secrets
  namespace: kcm-system
  labels:
    app.kubernetes.io/name: kcm-portal
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgres-db.kcm-system.svc.cluster.local:5432/kcm_db?sslmode=disable"
  NEXTAUTH_SECRET: "kcm-super-secret-production-auth-key-32-chars"
  NEXTAUTH_URL: "http://kcm-portal.local"
  CLOUDINARY_CLOUD_NAME: "demo"
  CLOUDINARY_API_KEY: "1234567890"
  CLOUDINARY_API_SECRET: "abcdefghijklmnopqrstuvwxyz"
  FIREBASE_PROJECT_ID: "kcm-project"
  FIREBASE_CLIENT_EMAIL: "service-account@kcm-project.iam.gserviceaccount.com"
  FIREBASE_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----\nKEY_DATA\n-----END RSA PRIVATE KEY-----\n"
