apiVersion: v2
name: redis
description: Helm Chart for Redis HA Cluster with Sentinel for KCM Church
type: application
version: 1.0.0
appVersion: "7.2.0"
keywords:
  - redis
  - cache
  - kcm-church
home: https://github.com/bunnyvalluri/church-
maintainers:
  - name: KCM Infra Team
    email: infra@kcmchurch.org
