apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/part-of: kcm-database-platform
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: kcm-database
  labels:
    app.kubernetes.io/name: kcm-postgresql
    app.kubernetes.io/part-of: kcm-database-platform
    pod-security.kubernetes.io/enforce: restricted
