apiVersion: v1
kind: Secret
metadata:
  name: kcm-db-superuser-secret
  namespace: kcm-database
  labels:
    app.kubernetes.io/name: kcm-postgresql
    app.kubernetes.io/part-of: kcm-database-platform
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: "KCM_DB_SUPERUSER_CHANGE_IN_VAULT_PROD_2026!"
---
apiVersion: v1
kind: Secret
metadata:
  name: kcm-db-app-secret
  namespace: kcm-database
  labels:
    app.kubernetes.io/name: kcm-postgresql
    app.kubernetes.io/part-of: kcm-database-platform
type: kubernetes.io/basic-auth
stringData:
  username: kcm_app_user
  password: "KCM_DB_APP_PASSWORD_CHANGE_IN_VAULT_PROD_2026!"
---
apiVersion: v1
kind: Secret
metadata:
  name: kcm-db-s3-backup-secret
  namespace: kcm-database
  labels:
    app.kubernetes.io/name: kcm-postgresql
    app.kubernetes.io/part-of: kcm-database-platform
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "KCM_S3_BACKUP_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "KCM_S3_BACKUP_SECRET_ACCESS_KEY"
