apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kcm-redis
  labels:
    app: kcm-redis
spec:
  serviceName: kcm-redis
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kcm-redis
  template:
    metadata:
      labels:
        app: kcm-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["redis-server", "--appendonly", "yes"]
          ports:
            - containerPort: 6379
              name: redis
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: kcm-redis
  labels:
    app: kcm-redis
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      name: redis
  selector:
    app: kcm-redis
