/**
 * frontend/tests/config/routes.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Central Route Registry for Kingdom of Christ Ministries Quality Engineering.
 * Provides a single source of truth for all routes across the 7 application groups:
 * PUBLIC, AUTH, PORTAL, ADMIN, MEMBER, PASTOR, EVENT_MANAGER / FIELD_VOLUNTEER.
 * ─────────────────────────────────────────────────────────────────────────────
 */

export type RouteCategory =
  | 'PUBLIC'
  | 'AUTH'
  | 'PORTAL'
  | 'ADMIN'
  | 'MEMBER'
  | 'PASTOR'
  | 'EVENT_MANAGER'
  | 'FIELD_VOLUNTEER';

export type UserRole =
  | 'SUPER_ADMIN'
  | 'ADMIN'
  | 'PASTOR'
  | 'MEMBER'
  | 'EVENT_MANAGER'
  | 'FIELD_VOLUNTEER'
  | 'NGO_ADMIN'
  | 'BRANCH_MANAGER'
  | 'MEDIA_TEAM';

export interface RouteDefinition {
  path: string;
  category: RouteCategory;
  requiresAuth: boolean;
  allowedRoles?: UserRole[];
  expectedStatus: number;
  expectedTitleRegex?: RegExp;
  isIndexed: boolean;
  description: string;
  expectedSelectors?: string[];
}

export const ROUTE_REGISTRY: RouteDefinition[] = [
  // ── 1. PUBLIC ROUTES ───────────────────────────────────────────────────────
  {
    path: '/',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Kingdom of Christ|KCM/i,
    isIndexed: true,
    description: 'Church Homepage with Hero, Live stream, Upcoming Events, and Ministries',
    expectedSelectors: ['#main-content', 'header', 'footer'],
  },
  {
    path: '/about',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /About|KCM/i,
    isIndexed: true,
    description: 'About KCM Overview',
  },
  {
    path: '/about/story',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Story|History|About/i,
    isIndexed: true,
    description: 'Our Journey & Story',
  },
  {
    path: '/about/leadership',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Leadership|Pastors|About/i,
    isIndexed: true,
    description: 'Pastoral & Ministry Leadership Team',
  },
  {
    path: '/about/beliefs',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Beliefs|Faith|About/i,
    isIndexed: true,
    description: 'Statement of Faith & Doctrinal Beliefs',
  },
  {
    path: '/about/ministries',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Ministries|About/i,
    isIndexed: true,
    description: 'Church Ministries (Youth, Women, Men, Children)',
  },
  {
    path: '/about/mission',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Mission|Vision|About/i,
    isIndexed: true,
    description: 'Mission, Vision & Global Outreach Purpose',
  },
  {
    path: '/sermons',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Sermon|Messages|KCM/i,
    isIndexed: true,
    description: 'Sermon Archive, Video/Audio Player & Series',
  },
  {
    path: '/events',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Events|Gatherings|KCM/i,
    isIndexed: true,
    description: 'Upcoming Events, Calendar & Registration',
  },
  {
    path: '/prayer',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Prayer|Requests|KCM/i,
    isIndexed: true,
    description: 'Prayer Request Submission & Prayer Wall',
  },
  {
    path: '/get-involved',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Get Involved|Serve|KCM/i,
    isIndexed: true,
    description: 'Serve and Connect Hub',
  },
  {
    path: '/get-involved/small-groups',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Small Groups|Cell Groups|Connect/i,
    isIndexed: true,
    description: 'Community & Bible Study Small Groups',
  },
  {
    path: '/get-involved/volunteer',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Volunteer|Serve|Get Involved/i,
    isIndexed: true,
    description: 'Volunteer Application & Service Teams',
  },
  {
    path: '/membership',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Membership|Join|KCM/i,
    isIndexed: true,
    description: 'Church Membership Information & Class Enrollment',
  },
  {
    path: '/locations',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Location|Campuses|Find Us/i,
    isIndexed: true,
    description: 'Campuses, Service Times & Interactive Map',
  },
  {
    path: '/gallery',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Gallery|Photos|KCM/i,
    isIndexed: true,
    description: 'Photo Gallery of Services, Conferences & Events',
  },
  {
    path: '/ngo',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /NGO|Charity|Foundation|Outreach/i,
    isIndexed: true,
    description: 'KCM Humanitarian & NGO Outreach Services',
  },
  {
    path: '/ngo/projects',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /NGO|Projects|Outreach/i,
    isIndexed: true,
    description: 'Humanitarian Relief & Community Projects',
  },
  {
    path: '/ngo/gallery',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /NGO|Gallery|Outreach/i,
    isIndexed: true,
    description: 'NGO Field Work Photo Gallery',
  },
  {
    path: '/ngo/videos',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /NGO|Videos|Stories/i,
    isIndexed: true,
    description: 'Impact Stories & Video Documentaries',
  },
  {
    path: '/ngo/volunteers',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /NGO|Volunteers|Field/i,
    isIndexed: true,
    description: 'NGO Volunteer Programs & Field Registration',
  },
  {
    path: '/ngo/donations',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /NGO|Donation|Give|Support/i,
    isIndexed: true,
    description: 'Dedicated NGO Charity Giving Portal',
  },
  {
    path: '/give',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Give|Tithes|Offerings|Donations/i,
    isIndexed: true,
    description: 'Church Tithes, Offerings & Online Giving',
  },
  {
    path: '/privacy',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Privacy Policy/i,
    isIndexed: true,
    description: 'Privacy Policy Document',
  },
  {
    path: '/terms',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Terms of Service|Terms/i,
    isIndexed: true,
    description: 'Terms of Service',
  },
  {
    path: '/offline',
    category: 'PUBLIC',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Offline|Connection/i,
    isIndexed: false,
    description: 'PWA Offline Fallback Page',
  },

  // ── 2. AUTH ROUTES ─────────────────────────────────────────────────────────
  {
    path: '/login',
    category: 'AUTH',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Sign In|Login|KCM/i,
    isIndexed: true,
    description: 'Secure Member, Pastor & Admin Login',
    expectedSelectors: ['input[type="email"]', 'input[type="password"]', 'button[type="submit"]'],
  },
  {
    path: '/register',
    category: 'AUTH',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Register|Sign Up|Join/i,
    isIndexed: true,
    description: 'New Member & Volunteer Registration',
    expectedSelectors: ['input[name="email"]', 'input[name="password"]'],
  },
  {
    path: '/forgot-password',
    category: 'AUTH',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Forgot Password|Reset/i,
    isIndexed: false,
    description: 'Password Recovery Request',
  },

  // ── 3. PORTAL SELECT ROUTE ─────────────────────────────────────────────────
  {
    path: '/portal-select',
    category: 'PORTAL',
    requiresAuth: false,
    expectedStatus: 200,
    expectedTitleRegex: /Portal|Choose Portal|Access/i,
    isIndexed: false,
    description: 'Direct Portal Destination Selector',
  },

  // ── 4. MEMBER PROTECTED ROUTES ─────────────────────────────────────────────
  {
    path: '/member',
    category: 'MEMBER',
    requiresAuth: true,
    allowedRoles: ['MEMBER', 'PASTOR', 'ADMIN', 'SUPER_ADMIN', 'EVENT_MANAGER', 'FIELD_VOLUNTEER'],
    expectedStatus: 200,
    expectedTitleRegex: /Member|Dashboard|KCM/i,
    isIndexed: false,
    description: 'Member Main Dashboard',
  },
  {
    path: '/member/profile',
    category: 'MEMBER',
    requiresAuth: true,
    allowedRoles: ['MEMBER', 'PASTOR', 'ADMIN', 'SUPER_ADMIN', 'EVENT_MANAGER', 'FIELD_VOLUNTEER'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Member Profile & Personal Information',
  },
  {
    path: '/member/events',
    category: 'MEMBER',
    requiresAuth: true,
    allowedRoles: ['MEMBER', 'PASTOR', 'ADMIN', 'SUPER_ADMIN', 'EVENT_MANAGER', 'FIELD_VOLUNTEER'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Member Registered Events & Tickets',
  },
  {
    path: '/member/prayers',
    category: 'MEMBER',
    requiresAuth: true,
    allowedRoles: ['MEMBER', 'PASTOR', 'ADMIN', 'SUPER_ADMIN', 'EVENT_MANAGER', 'FIELD_VOLUNTEER'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Member Submitted Prayer Requests & Updates',
  },
  {
    path: '/member/sermons',
    category: 'MEMBER',
    requiresAuth: true,
    allowedRoles: ['MEMBER', 'PASTOR', 'ADMIN', 'SUPER_ADMIN', 'EVENT_MANAGER', 'FIELD_VOLUNTEER'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Member Bookmarked & Liked Sermons',
  },
  {
    path: '/member/volunteer',
    category: 'MEMBER',
    requiresAuth: true,
    allowedRoles: ['MEMBER', 'PASTOR', 'ADMIN', 'SUPER_ADMIN', 'EVENT_MANAGER', 'FIELD_VOLUNTEER'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Member Volunteer Schedules & Assignments',
  },
  {
    path: '/member/give',
    category: 'MEMBER',
    requiresAuth: true,
    allowedRoles: ['MEMBER', 'PASTOR', 'ADMIN', 'SUPER_ADMIN', 'EVENT_MANAGER', 'FIELD_VOLUNTEER'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Member Giving History & Tax Receipts',
  },

  // ── 5. PASTOR PROTECTED ROUTES ─────────────────────────────────────────────
  {
    path: '/pastor/dashboard',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    expectedTitleRegex: /Pastor|Ministry|KCM/i,
    isIndexed: false,
    description: 'Pastor Executive Ministry Dashboard',
  },
  {
    path: '/pastor/main/sermons',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Pastor Sermon Management & Outline Notes',
  },
  {
    path: '/pastor/main/donations',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Pastor Giving Summaries & Fund Oversight',
  },
  {
    path: '/pastor/main/member-requests',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Pastoral Counseling & Member Appointment Requests',
  },
  {
    path: '/pastor/main/prayer-requests',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Pastoral Care Prayer Review & Ministry Intercession',
  },
  {
    path: '/pastor/main/events',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Pastoral Event Calendar & Service Planning',
  },
  {
    path: '/pastor/main/messages',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Pastoral Broadcasts & Congregation Messaging',
  },
  {
    path: '/pastor/ministry/bible-study-groups',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Bible Study Curriculum & Small Group Oversight',
  },
  {
    path: '/pastor/ministry/small-groups',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Cell Groups Leadership Oversight',
  },
  {
    path: '/pastor/ministry/volunteers',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Ministry Volunteers Roster & Leadership Training',
  },
  {
    path: '/pastor/ngo/projects',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Pastoral Oversight of NGO Mission Projects',
  },
  {
    path: '/pastor/ngo/media',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'NGO Mission Media & Field Testimonials',
  },
  {
    path: '/pastor/ngo/volunteers',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'NGO Mission Volunteer Deployment',
  },
  {
    path: '/pastor/reports/attendance',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Pastoral Service Attendance Reports',
  },
  {
    path: '/pastor/reports/members',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Pastoral Congregation Growth Analytics',
  },
  {
    path: '/pastor/reports/finance',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Pastoral Ministry Financial Overview',
  },
  {
    path: '/pastor/reports/growth',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Ministry Metric Trajectory & Growth Reports',
  },
  {
    path: '/pastor/calendar',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Pastoral Schedule & Ministry Calendar',
  },
  {
    path: '/pastor/media/gallery',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Pastoral Media Assets Gallery',
  },
  {
    path: '/pastor/media/videos',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Pastoral Sermon Videos & Livestream Archives',
  },
  {
    path: '/pastor/media/documents',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Pastoral Ministry Documents & Study Guides',
  },
  {
    path: '/pastor/profile',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Pastor Profile Management',
  },
  {
    path: '/pastor/settings/general',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Pastor Portal Preferences',
  },
  {
    path: '/pastor/settings/security',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Pastor Account Security & Credentials',
  },
  {
    path: '/pastor/settings/notifications',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Pastor Alert & Notification Channels',
  },
  {
    path: '/pastor/settings/preferences',
    category: 'PASTOR',
    requiresAuth: true,
    allowedRoles: ['PASTOR', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Pastor Ministry Portal Customizations',
  },

  // ── 6. ADMIN PROTECTED ROUTES ─────────────────────────────────────────────
  {
    path: '/admin/dashboard',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    expectedTitleRegex: /Admin|Control|KCM/i,
    isIndexed: false,
    description: 'Super-Admin Executive Operations Dashboard',
  },
  {
    path: '/admin/openclaw-orchestrator',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'OpenClaw Autonomous Workflow Orchestrator Engine',
  },
  {
    path: '/admin/members',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Congregation Directory & User Account Administration',
  },
  {
    path: '/admin/members/member',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Detailed Member Record Management',
  },
  {
    path: '/admin/members/groups',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Ministry & Small Group Allocations',
  },
  {
    path: '/admin/members/prayer-requests',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Prayer Request Moderation & Assignment',
  },
  {
    path: '/admin/members/family-management',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Family Household Units & Relationship Linking',
  },
  {
    path: '/admin/finance',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Finance & Treasury Management Console',
  },
  {
    path: '/admin/finance/donations',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Donations & Tithes Ledger',
  },
  {
    path: '/admin/finance/pledges',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Capital Campaign & Building Fund Pledges',
  },
  {
    path: '/admin/finance/transactions',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Stripe, Razorpay & Offline Transaction Records',
  },
  {
    path: '/admin/finance/accounts',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Bank & Church Fund Accounting Chart',
  },
  {
    path: '/admin/attendance',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Attendance & Check-in Control System',
  },
  {
    path: '/admin/attendance/records',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Service Attendance Logs & History',
  },
  {
    path: '/admin/attendance/events',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Event Check-in QR Scanners & Headcounts',
  },
  {
    path: '/admin/attendance/reports',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Attendance Trends & Headcount Visualizations',
  },
  {
    path: '/admin/content',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Global Church Content Management System',
  },
  {
    path: '/admin/content/sermons',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Sermon Publishing & Media Upload',
  },
  {
    path: '/admin/content/events',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Church Events Creation & Seat Limits',
  },
  {
    path: '/admin/content/announcements',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Banner & Broadcast Announcements',
  },
  {
    path: '/admin/content/media',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Cloudinary Media Asset Library Management',
  },
  {
    path: '/admin/content/pages',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'CMS Dynamic Page Content Editor',
  },
  {
    path: '/admin/ngo',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN', 'NGO_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'NGO Mission Projects & Global Relief Administration',
  },
  {
    path: '/admin/ngo/projects',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN', 'NGO_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'NGO Relief Projects Creation & Statuses',
  },
  {
    path: '/admin/ngo/media',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN', 'NGO_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'NGO Field Photo & Video Moderation',
  },
  {
    path: '/admin/ngo/volunteers',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN', 'NGO_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'NGO Relief Volunteer Deployment & Approvals',
  },
  {
    path: '/admin/settings',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Platform Global Configuration Settings',
  },
  {
    path: '/admin/settings/general',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'System General Configuration & Branding',
  },
  {
    path: '/admin/settings/users',
    category: 'ADMIN',
    requiresAuth: true,
    allowedRoles: ['ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'System Users, Staff Roles & Permissions Access Control',
  },

  // ── 7. EVENT MANAGER & FIELD VOLUNTEER ROUTES ─────────────────────────────
  {
    path: '/event-manager',
    category: 'EVENT_MANAGER',
    requiresAuth: true,
    allowedRoles: ['EVENT_MANAGER', 'FIELD_VOLUNTEER', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    expectedTitleRegex: /Event|Volunteer|Manager/i,
    isIndexed: false,
    description: 'Event Management & On-Site Coordinator Dashboard',
  },
  {
    path: '/event-manager/report',
    category: 'EVENT_MANAGER',
    requiresAuth: true,
    allowedRoles: ['EVENT_MANAGER', 'FIELD_VOLUNTEER', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Post-Event Incident & Headcount Summary Reports',
  },
  {
    path: '/field-volunteer',
    category: 'FIELD_VOLUNTEER',
    requiresAuth: true,
    allowedRoles: ['FIELD_VOLUNTEER', 'EVENT_MANAGER', 'ADMIN', 'SUPER_ADMIN'],
    expectedStatus: 200,
    isIndexed: false,
    description: 'Field Volunteer Task Allocation & Fast Check-In',
  },
];

/**
 * Filter helpers
 */
export const getPublicRoutes = () => ROUTE_REGISTRY.filter((r) => r.category === 'PUBLIC');
export const getAuthRoutes = () => ROUTE_REGISTRY.filter((r) => r.category === 'AUTH');
export const getAdminRoutes = () => ROUTE_REGISTRY.filter((r) => r.category === 'ADMIN');
export const getPastorRoutes = () => ROUTE_REGISTRY.filter((r) => r.category === 'PASTOR');
export const getMemberRoutes = () => ROUTE_REGISTRY.filter((r) => r.category === 'MEMBER');
export const getEventManagerRoutes = () => ROUTE_REGISTRY.filter((r) => r.category === 'EVENT_MANAGER' || r.category === 'FIELD_VOLUNTEER');
export const getProtectedRoutes = () => ROUTE_REGISTRY.filter((r) => r.requiresAuth);
