apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kcm-kafka.fullname" . }}-pdb
  namespace: {{ .Values.global.namespace }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
      app.kubernetes.io/instance: {{ .Release.Name }}
