apiVersion: v1
kind: Service
metadata:
  name: {{ include "kcm-kafka.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: client
      port: 9092
      targetPort: client
    - name: controller
      port: 9093
      targetPort: controller
    - name: internal
      port: 9094
      targetPort: internal
    - name: jmx
      port: 9308
      targetPort: jmx-metrics
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kcm-kafka.fullname" . }}-headless
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: client
      port: 9092
      targetPort: client
    - name: controller
      port: 9093
      targetPort: controller
    - name: internal
      port: 9094
      targetPort: internal
    - name: jmx
      port: 9308
      targetPort: jmx-metrics
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: {{ .Release.Name }}
