apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-platform
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: kcm-platform
    app.kubernetes.io/component: logging
spec:
  project: default
  source:
    repoURL: 'https://github.com/bunnyvalluri/church-.git'
    targetRevision: HEAD
    path: platform/logging/helm
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
