apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  # In a real production scenario, this should be managed by ExternalSecrets or SealedSecrets
  # Here we just leave it blank or populate with a dummy value to avoid errors
  DUMMY_SECRET: "YmFzZTY0"
