apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

helmCharts:
- name: kcm-portal
  repo: ../../../../helm/kcm-portal
  releaseName: kcm-portal
  namespace: kcm-staging
  valuesFile: values-staging.yaml

namespace: kcm-staging
