frontend:
  replicaCount: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4

ingress:
  hosts:
    - host: api.staging.kcmchurch.local
      paths:
        - path: /api
          pathType: Prefix
          backend: api
        - path: /socket.io
          pathType: Prefix
          backend: socket
    - host: staging.kcmchurch.local
      paths:
        - path: /
          pathType: Prefix
          backend: frontend
  tls:
    - secretName: kcmchurch-staging-tls
      hosts:
        - staging.kcmchurch.local
        - api.staging.kcmchurch.local

env:
  NODE_ENV: staging
