apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  alert.rules: |
    groups:
      - name: KCMAlertRules
        rules:
          - alert: HighHTTPErrorRate
            expr: sum(rate(http_requests_total{status=~"5.*"}[5m])) / sum(rate(http_requests_total[5m])) * 100 > 1
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: "High HTTP 5xx error rate detected (> 1%)"
              description: "KCM Portal HTTP error rate is currently {{ $value }}%"

          - alert: PodCrashLooping
            expr: rate(kube_pod_container_status_restarts_total[5m]) * 60 > 2
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Pod {{ $labels.pod }} is crash looping"

          - alert: HighDatabaseMemoryUsage
            expr: container_memory_usage_bytes{container="postgres"} / container_spec_memory_limit_bytes{container="postgres"} * 100 > 85
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "PostgreSQL Database memory usage is exceeding 85%"
