# Production values will leverage full HA and autoscaling settings

frontend:
  replicaCount: 3
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 15
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

api:
  replicaCount: 3
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

socket:
  replicaCount: 3
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 20
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

worker:
  replicaCount: 2
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

ingress:
  hosts:
    - host: api.kcmchurch.org # Assuming .org for prod, adjust based on user feedback
      paths:
        - path: /api
          pathType: Prefix
          backend: api
        - path: /socket.io
          pathType: Prefix
          backend: socket
    - host: kcmchurch.org
      paths:
        - path: /
          pathType: Prefix
          backend: frontend
  tls:
    - secretName: kcmchurch-prod-tls
      hosts:
        - kcmchurch.org
        - api.kcmchurch.org

env:
  NODE_ENV: production
