# Development Overrides for Backend Chart
replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: false

dbMigration:
  enabled: false

env:
  NODE_ENV: "development"
