driver:
  kind: modern_ebpf

falcosidekick:
  enabled: true
  config:
    slack:
      webhookurl: "https://hooks.slack.com/services/KCM/SECURITY/ALERTS"
      minimumpriority: "warning"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
