apiVersion: v1
kind: Secret
metadata:
  name: longhorn-s3-backup-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "KCM_S3_LONGHORN_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "KCM_S3_LONGHORN_SECRET_ACCESS_KEY"
  AWS_END_POINT: "https://s3.us-east-1.amazonaws.com"
  AWS_CERT: ""
