auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info

memberlist:
  join_members:
    - loki-memberlist.logging.svc.cluster.local:7946

common:
  path_prefix: /var/loki
  storage:
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  replication_factor: 3
  ring:
    kvstore:
      store: memberlist

schema_config:
  configs:
    - from: "2024-01-01"
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: loki_index_
        period: 24h

limits_config:
  retention_period: 30d
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_cache_freshness_per_query: 10m
  split_queries_by_interval: 15m
  max_query_parallelism: 32
  ingestion_rate_mb: 32
  ingestion_burst_size_mb: 64

compactor:
  working_directory: /var/loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h

ruler:
  enable_api: true
  storage:
    type: local
    local:
      directory: /var/loki/rules
  rule_path: /tmp/loki/scratch
  alertmanager_url: http://alertmanager-operated.monitoring.svc.cluster.local:9093
