import { isBranchMatch } from './galleryData';
/**
 * Gallery Videos Data — Kingdom of Christ Ministries
 * All 44 embedded YouTube video entries for the /gallery Videos section.
 */

export type VideoCategory =
  | "All"
  | "Revival & Blessings"
  | "Christmas Events"
  | "Worship & Praise"
  | "Youth & Children"
  | "Special Services";

export interface GalleryVideoItem {
  branchId: string;
  branchName: string;
  branchSlug: string;
  id: string;
  videoId: string;
  title: string;
  titleTe?: string;
  titleHi?: string;
  description: string;
  category: VideoCategory;
  date: string;
  embedUrl: string;
  thumbnail: string;
  /** optional si param from the share URL */
  siParam?: string;
}

// All 44 video entries from the /gallery page YouTube embeds
export const GALLERY_VIDEO_ITEMS: GalleryVideoItem[] = [
  {
    id: "kcm-video-01",
    branchId: "cmskewevf0000lz9gnoh1n8ve",
    branchName: "Shapur Nagar",
    branchSlug: "shapur-nagar",
    videoId: "B1M_Ls_vi4o",
    title: "KCM August 2026 — Blessing Gathering Making Video",
    titleTe: "కింగ్డమ్ ఆఫ్ క్రైస్ట్ మినిస్ట్రీస్ 2026 ఆగస్టు ఆశీర్వాద కూడిక 🙏",
    titleHi: "KCM 2026 अगस्त — आशीष सभा मेकिंग वीडियो",
    description: "A special making video of the Kingdom of Christ Ministries August 2026 blessing gathering service.",
    category: "Revival & Blessings",
    date: "August 2026",
    embedUrl: "https://www.youtube.com/embed/B1M_Ls_vi4o?si=UKv6_U8btJNI751K",
    thumbnail: "https://i.ytimg.com/vi/B1M_Ls_vi4o/hqdefault.jpg",
    siParam: "UKv6_U8btJNI751K",
  },
  {
    id: "kcm-video-02",
    branchId: "cmskewevf0000lz9gnoh1n8ve",
    branchName: "Shapur Nagar",
    branchSlug: "shapur-nagar",
    videoId: "WKborYLfJKY",
    title: "Christmas Event 2025 — KCM Making Video",
    titleTe: "క్రిస్మస్ ఈవెంట్ 2025 — కింగ్డమ్ ఆఫ్ క్రైస్ట్ మేకింగ్",
    titleHi: "क्रिसमस इवेंट 2025 — KCM मेकिंग वीडियो",
    description: "Behind-the-scenes making of the grand Christmas event 2025 at Kingdom of Christ Ministries church.",
    category: "Christmas Events",
    date: "December 2025",
    embedUrl: "https://www.youtube.com/embed/WKborYLfJKY?si=ljWCOqWasXrnGr45",
    thumbnail: "https://i.ytimg.com/vi/WKborYLfJKY/hqdefault.jpg",
    siParam: "ljWCOqWasXrnGr45",
  },
  {
    id: "kcm-video-03",
    branchId: "cmskewevf0000lz9gnoh1n8ve",
    branchName: "Shapur Nagar",
    branchSlug: "shapur-nagar",
    videoId: "pwm60SVNAJM",
    title: "KCM Church Service — December 26, 2023",
    titleTe: "KCM చర్చి సేవ — డిసెంబర్ 26, 2023",
    titleHi: "KCM चर्च सेवा — 26 दिसंबर 2023",
    description: "Kingdom of Christ Ministries church gathering and praise service from December 26, 2023.",
    category: "Worship & Praise",
    date: "December 26, 2023",
    embedUrl: "https://www.youtube.com/embed/pwm60SVNAJM?si=hw_noSLMgLpPZNO1",
    thumbnail: "https://i.ytimg.com/vi/pwm60SVNAJM/hqdefault.jpg",
    siParam: "hw_noSLMgLpPZNO1",
  },
  {
    id: "kcm-video-04",
    branchId: "cmskewevf0000lz9gnoh1n8ve",
    branchName: "Shapur Nagar",
    branchSlug: "shapur-nagar",
    videoId: "qoVeMtHxFdI",
    title: "KCM Christmas Celebration — December 24, 2023",
    titleTe: "KCM క్రిస్మస్ వేడుక — డిసెంబర్ 24, 2023",
    titleHi: "KCM क्रिसमस उत्सव — 24 दिसंबर 2023",
    description: "Joyful Christmas Eve celebration service at Kingdom of Christ Ministries, December 24, 2023.",
    category: "Christmas Events",
    date: "December 24, 2023",
    embedUrl: "https://www.youtube.com/embed/qoVeMtHxFdI?si=AqXKiwARllFJFkSW",
    thumbnail: "https://i.ytimg.com/vi/qoVeMtHxFdI/hqdefault.jpg",
    siParam: "AqXKiwARllFJFkSW",
  },
  {
    id: "kcm-video-05",
    branchId: "cmskewevf0000lz9gnoh1n8ve",
    branchName: "Shapur Nagar",
    branchSlug: "shapur-nagar",
    videoId: "RrnjAWNPZQo",
    title: "KCM Christmas Part 2 — December 24, 2023",
    titleTe: "KCM క్రిస్మస్ భాగం 2 — డిసెంబర్ 24, 2023",
    titleHi: "KCM क्रिसमस भाग 2 — 24 दिसंबर 2023",
    description: "Continuation of the Christmas Eve worship and ministry service at KCM, December 24, 2023.",
    category: "Christmas Events",
    date: "December 24, 2023",
    embedUrl: "https://www.youtube.com/embed/RrnjAWNPZQo?si=Ylg5pOPaXQ8sL3H8",
    thumbnail: "https://i.ytimg.com/vi/RrnjAWNPZQo/hqdefault.jpg",
    siParam: "Ylg5pOPaXQ8sL3H8",
  },
  {
    id: "kcm-video-06",
    branchId: "cmskewevf0000lz9gnoh1n8ve",
    branchName: "Shapur Nagar",
    branchSlug: "shapur-nagar",
    videoId: "3ECD57HpiW8",
    title: "KCM Church Gathering — December 26, 2023",
    titleTe: "KCM చర్చి కూడిక — డిసెంబర్ 26, 2023",
    titleHi: "KCM कलीसिया सभा — 26 दिसंबर 2023",
    description: "Kingdom of Christ Ministries full gathering service from December 26, 2023.",
    category: "Worship & Praise",
    date: "December 26, 2023",
    embedUrl: "https://www.youtube.com/embed/3ECD57HpiW8?si=MBbRpLAOxwTn_d4I",
    thumbnail: "https://i.ytimg.com/vi/3ECD57HpiW8/hqdefault.jpg",
    siParam: "MBbRpLAOxwTn_d4I",
  },
  {
    id: "kcm-video-07",
    branchId: "cmskewevf0000lz9gnoh1n8ve",
    branchName: "Shapur Nagar",
    branchSlug: "shapur-nagar",
    videoId: "n0Y1OIFUmOQ",
    title: "KCM Praise & Worship — December 26, 2023",
    titleTe: "KCM స్తుతి & ఆరాధన — డిసెంబర్ 26, 2023",
    titleHi: "KCM स्तुति और आराधना — 26 दिसंबर 2023",
    description: "Vibrant praise and worship session from Kingdom of Christ Ministries, December 26, 2023.",
    category: "Worship & Praise",
    date: "December 26, 2023",
    embedUrl: "https://www.youtube.com/embed/n0Y1OIFUmOQ?si=OhxINHeFRyomvfAI",
    thumbnail: "https://i.ytimg.com/vi/n0Y1OIFUmOQ/hqdefault.jpg",
    siParam: "OhxINHeFRyomvfAI",
  },
  {
    id: "kcm-video-08",
    branchId: "cmskewevf0000lz9gnoh1n8ve",
    branchName: "Shapur Nagar",
    branchSlug: "shapur-nagar",
    videoId: "9NC5G5FPD7w",
    title: "KCM Ministry Moments — December 26, 2023",
    titleTe: "KCM మినిస్ట్రీ క్షణాలు — డిసెంబర్ 26, 2023",
    titleHi: "KCM सेवकाई क्षण — 26 दिसंबर 2023",
    description: "Captured ministry moments from the December 26, 2023 service at Kingdom of Christ Ministries.",
    category: "Special Services",
    date: "December 26, 2023",
    embedUrl: "https://www.youtube.com/embed/9NC5G5FPD7w?si=ObYjlWNszNPxktyc",
    thumbnail: "https://i.ytimg.com/vi/9NC5G5FPD7w/hqdefault.jpg",
    siParam: "ObYjlWNszNPxktyc",
  },
  {
    id: "kcm-video-09",
    branchId: "cmskewevf0000lz9gnoh1n8ve",
    branchName: "Shapur Nagar",
    branchSlug: "shapur-nagar",
    videoId: "cVgrgJGOSCQ",
    title: "KCM Service Highlights — December 26, 2023",
    titleTe: "KCM సేవా హైలైట్స్ — డిసెంబర్ 26, 2023",
    titleHi: "KCM सेवा हाइलाइट्स — 26 दिसंबर 2023",
    description: "Service highlights and special moments from KCM December 26, 2023 gathering.",
    category: "Special Services",
    date: "December 26, 2023",
    embedUrl: "https://www.youtube.com/embed/cVgrgJGOSCQ?si=JFTVvQaunAyJaemz",
    thumbnail: "https://i.ytimg.com/vi/cVgrgJGOSCQ/hqdefault.jpg",
    siParam: "JFTVvQaunAyJaemz",
  },
  {
    id: "kcm-video-10",
    branchId: "cmskewevf0000lz9gnoh1n8ve",
    branchName: "Shapur Nagar",
    branchSlug: "shapur-nagar",
    videoId: "r2G7XGBMnUY",
    title: "KCM Fellowship Video — December 26, 2023",
    titleTe: "KCM సహవాస వీడియో — డిసెంబర్ 26, 2023",
    titleHi: "KCM संगति वीडियो — 26 दिसंबर 2023",
    description: "Beautiful fellowship moments captured at Kingdom of Christ Ministries, December 26, 2023.",
    category: "Worship & Praise",
    date: "December 26, 2023",
    embedUrl: "https://www.youtube.com/embed/r2G7XGBMnUY?si=COyq5sfAwUE3DDEv",
    thumbnail: "https://i.ytimg.com/vi/r2G7XGBMnUY/hqdefault.jpg",
    siParam: "COyq5sfAwUE3DDEv",
  },
  {
    id: "kcm-video-11",
    branchId: "cmskewevf0000lz9gnoh1n8ve",
    branchName: "Shapur Nagar",
    branchSlug: "shapur-nagar",
    videoId: "099g2qh8ed0",
    title: "KCM Christmas Programme — December 20, 2024",
    titleTe: "KCM క్రిస్మస్ కార్యక్రమం — డిసెంబర్ 20, 2024",
    titleHi: "KCM क्रिसमस कार्यक्रम — 20 दिसंबर 2024",
    description: "Kingdom of Christ Ministries annual Christmas programme recorded on December 20, 2024.",
    category: "Christmas Events",
    date: "December 20, 2024",
    embedUrl: "https://www.youtube.com/embed/099g2qh8ed0?si=JI_Ga-zQ5WRQIRlx",
    thumbnail: "https://i.ytimg.com/vi/099g2qh8ed0/hqdefault.jpg",
    siParam: "JI_Ga-zQ5WRQIRlx",
  },
  {
    id: "kcm-video-12",
    branchId: "cmskewevf0000lz9gnoh1n8ve",
    branchName: "Shapur Nagar",
    branchSlug: "shapur-nagar",
    videoId: "099g2qh8ed0",
    title: "KCM Christmas Programme Part 2 — December 20, 2024",
    titleTe: "KCM క్రిస్మస్ కార్యక్రమం భాగం 2 — డిసెంబర్ 20, 2024",
    titleHi: "KCM क्रिसमस कार्यक्रम भाग 2 — 20 दिसंबर 2024",
    description: "Part 2 of the Kingdom of Christ Ministries Christmas programme, December 20, 2024.",
    category: "Christmas Events",
    date: "December 20, 2024",
    embedUrl: "https://www.youtube.com/embed/099g2qh8ed0?si=JI_Ga-zQ5WRQIRlx",
    thumbnail: "https://i.ytimg.com/vi/099g2qh8ed0/hqdefault.jpg",
    siParam: "JI_Ga-zQ5WRQIRlx",
  },
  {
    id: "kcm-video-13",
    branchId: "cmskewevf0000lz9gnoh1n8ve",
    branchName: "Shapur Nagar",
    branchSlug: "shapur-nagar",
    videoId: "QXbFUyeN5Us",
    title: "KCM Youth Performance — December 20, 2024",
    titleTe: "KCM యువత ప్రదర్శన — డిసెంబర్ 20, 2024",
    titleHi: "KCM युवा प्रदर्शन — 20 दिसंबर 2024",
    description: "Special youth performance and dance at Kingdom of Christ Ministries, December 20, 2024.",
    category: "Youth & Children",
    date: "December 20, 2024",
    embedUrl: "https://www.youtube.com/embed/QXbFUyeN5Us?si=dH4uugfDH2RxAv_6",
    thumbnail: "https://i.ytimg.com/vi/QXbFUyeN5Us/hqdefault.jpg",
    siParam: "dH4uugfDH2RxAv_6",
  },
  {
    id: "kcm-video-14",
    branchId: "cmskewevf0000lz9gnoh1n8ve",
    branchName: "Shapur Nagar",
    branchSlug: "shapur-nagar",
    videoId: "czVLAc3B3mA",
    title: "KCM Children's Worship — December 20, 2024",
    titleTe: "KCM పిల్లల ఆరాధన — డిసెంబర్ 20, 2024",
    titleHi: "KCM बच्चों की आराधना — 20 दिसंबर 2024",
    description: "Heartwarming children's worship and performance at KCM Christmas, December 20, 2024.",
    category: "Youth & Children",
    date: "December 20, 2024",
    embedUrl: "https://www.youtube.com/embed/czVLAc3B3mA?si=0UBDHAkUUWqb5mk_",
    thumbnail: "https://i.ytimg.com/vi/czVLAc3B3mA/hqdefault.jpg",
    siParam: "0UBDHAkUUWqb5mk_",
  },
  {
    id: "kcm-video-15",
    branchId: "cmskewevf0000lz9gnoh1n8ve",
    branchName: "Shapur Nagar",
    branchSlug: "shapur-nagar",
    videoId: "iqkhqGxmLJg",
    title: "KCM Praise Dance — December 20, 2024",
    titleTe: "KCM స్తుతి నృత్యం — డిసెంబర్ 20, 2024",
    titleHi: "KCM स्तुति नृत्य — 20 दिसंबर 2024",
    description: "Inspiring praise dance presentation at Kingdom of Christ Ministries, December 20, 2024.",
    category: "Worship & Praise",
    date: "December 20, 2024",
    embedUrl: "https://www.youtube.com/embed/iqkhqGxmLJg?si=vmMNANVCvIDOXiKv",
    thumbnail: "https://i.ytimg.com/vi/iqkhqGxmLJg/hqdefault.jpg",
    siParam: "vmMNANVCvIDOXiKv",
  },
  {
    id: "kcm-video-16",
    branchId: "cmskewevf0000lz9gnoh1n8ve",
    branchName: "Shapur Nagar",
    branchSlug: "shapur-nagar",
    videoId: "FQJLrS3-v_8",
    title: "KCM Musical Worship — December 20, 2024",
    titleTe: "KCM సంగీత ఆరాధన — డిసెంబర్ 20, 2024",
    titleHi: "KCM संगीत आराधना — 20 दिसंबर 2024",
    description: "Musical worship and praise session at Kingdom of Christ Ministries, December 20, 2024.",
    category: "Worship & Praise",
    date: "December 20, 2024",
    embedUrl: "https://www.youtube.com/embed/FQJLrS3-v_8?si=NjA7RQqewEyP9ntA",
    thumbnail: "https://i.ytimg.com/vi/FQJLrS3-v_8/hqdefault.jpg",
    siParam: "NjA7RQqewEyP9ntA",
  },
  {
    id: "kcm-video-17",
    branchId: "cmrgwqhc30001fsk8mysbmp50",
    branchName: "Subhash Nagar",
    branchSlug: "subhash-nagar",
    videoId: "36DmlTZu0Aw",
    title: "KCM Christmas Drama — December 20, 2024",
    titleTe: "KCM క్రిస్మస్ నాటకం — డిసెంబర్ 20, 2024",
    titleHi: "KCM क्रिसमस नाटक — 20 दिसंबर 2024",
    description: "A touching Christmas drama presentation at Kingdom of Christ Ministries, December 20, 2024.",
    category: "Christmas Events",
    date: "December 20, 2024",
    embedUrl: "https://www.youtube.com/embed/36DmlTZu0Aw?si=dyaI4DAPfv8G2ShB",
    thumbnail: "https://i.ytimg.com/vi/36DmlTZu0Aw/hqdefault.jpg",
    siParam: "dyaI4DAPfv8G2ShB",
  },
  {
    id: "kcm-video-18",
    branchId: "cmrgwqhc30001fsk8mysbmp50",
    branchName: "Subhash Nagar",
    branchSlug: "subhash-nagar",
    videoId: "r7Wy7HopKeo",
    title: "KCM Church Service — December 20, 2024",
    titleTe: "KCM చర్చి సేవ — డిసెంబర్ 20, 2024",
    titleHi: "KCM चर्च सेवा — 20 दिसंबर 2024",
    description: "Kingdom of Christ Ministries December 2024 church service highlights and worship.",
    category: "Special Services",
    date: "December 20, 2024",
    embedUrl: "https://www.youtube.com/embed/r7Wy7HopKeo?si=GiwkckPf6lqgbR8u",
    thumbnail: "https://i.ytimg.com/vi/r7Wy7HopKeo/hqdefault.jpg",
    siParam: "GiwkckPf6lqgbR8u",
  },
  {
    id: "kcm-video-19",
    branchId: "cmrgwqhc30001fsk8mysbmp50",
    branchName: "Subhash Nagar",
    branchSlug: "subhash-nagar",
    videoId: "fj89pm0jQdc",
    title: "KCM Christmas Celebration — December 26, 2024",
    titleTe: "KCM క్రిస్మస్ వేడుక — డిసెంబర్ 26, 2024",
    titleHi: "KCM क्रिसमस उत्सव — 26 दिसंबर 2024",
    description: "Grand Christmas celebration service at Kingdom of Christ Ministries, December 26, 2024.",
    category: "Christmas Events",
    date: "December 26, 2024",
    embedUrl: "https://www.youtube.com/embed/fj89pm0jQdc?si=zfydui78Ej4kiJ-K",
    thumbnail: "https://i.ytimg.com/vi/fj89pm0jQdc/hqdefault.jpg",
    siParam: "zfydui78Ej4kiJ-K",
  },
  {
    id: "kcm-video-20",
    branchId: "cmrgwqhc30001fsk8mysbmp50",
    branchName: "Subhash Nagar",
    branchSlug: "subhash-nagar",
    videoId: "zwaW_PJRdFY",
    title: "KCM Worship & Praise — December 26, 2024",
    titleTe: "KCM ఆరాధన & స్తుతి — డిసెంబర్ 26, 2024",
    titleHi: "KCM आराधना और स्तुति — 26 दिसंबर 2024",
    description: "Spirit-filled worship and praise at Kingdom of Christ Ministries, December 26, 2024.",
    category: "Worship & Praise",
    date: "December 26, 2024",
    embedUrl: "https://www.youtube.com/embed/zwaW_PJRdFY?si=meyuC-itTpIiwZ3V",
    thumbnail: "https://i.ytimg.com/vi/zwaW_PJRdFY/hqdefault.jpg",
    siParam: "meyuC-itTpIiwZ3V",
  },
  {
    id: "kcm-video-21",
    branchId: "cmrgwqhc30001fsk8mysbmp50",
    branchName: "Subhash Nagar",
    branchSlug: "subhash-nagar",
    videoId: "UmHFyjvmD-g",
    title: "KCM Youth Ministry — December 26, 2024",
    titleTe: "KCM యువత మినిస్ట్రీ — డిసెంబర్ 26, 2024",
    titleHi: "KCM युवा सेवकाई — 26 दिसंबर 2024",
    description: "Dynamic youth ministry performance at Kingdom of Christ Ministries, December 26, 2024.",
    category: "Youth & Children",
    date: "December 26, 2024",
    embedUrl: "https://www.youtube.com/embed/UmHFyjvmD-g?si=1m-yAgS4kEH3U4P7",
    thumbnail: "https://i.ytimg.com/vi/UmHFyjvmD-g/hqdefault.jpg",
    siParam: "1m-yAgS4kEH3U4P7",
  },
  {
    id: "kcm-video-22",
    branchId: "cmrgwqhc30001fsk8mysbmp50",
    branchName: "Subhash Nagar",
    branchSlug: "subhash-nagar",
    videoId: "HvrHo2VgPpg",
    title: "KCM Fellowship & Praise — December 26, 2024",
    titleTe: "KCM సహవాసం & స్తుతి — డిసెంబర్ 26, 2024",
    titleHi: "KCM संगति और स्तुति — 26 दिसंबर 2024",
    description: "Fellowship and praise session at Kingdom of Christ Ministries Christmas gathering, December 26, 2024.",
    category: "Worship & Praise",
    date: "December 26, 2024",
    embedUrl: "https://www.youtube.com/embed/HvrHo2VgPpg?si=DheTbi763HTstQ5X",
    thumbnail: "https://i.ytimg.com/vi/HvrHo2VgPpg/hqdefault.jpg",
    siParam: "DheTbi763HTstQ5X",
  },
  {
    id: "kcm-video-23",
    branchId: "cmrgwqhc30001fsk8mysbmp50",
    branchName: "Subhash Nagar",
    branchSlug: "subhash-nagar",
    videoId: "mDW4K285ALE",
    title: "KCM Christmas Service — December 26, 2024",
    titleTe: "KCM క్రిస్మస్ సేవ — డిసెంబర్ 26, 2024",
    titleHi: "KCM क्रिसमस सेवा — 26 दिसंबर 2024",
    description: "Special Christmas day church service at Kingdom of Christ Ministries, December 26, 2024.",
    category: "Christmas Events",
    date: "December 26, 2024",
    embedUrl: "https://www.youtube.com/embed/mDW4K285ALE?si=VaiLfdKeoZ2MwkdB",
    thumbnail: "https://i.ytimg.com/vi/mDW4K285ALE/hqdefault.jpg",
    siParam: "VaiLfdKeoZ2MwkdB",
  },
  {
    id: "kcm-video-24",
    branchId: "cmrgwqhc30001fsk8mysbmp50",
    branchName: "Subhash Nagar",
    branchSlug: "subhash-nagar",
    videoId: "6wVR2p6EvMI",
    title: "KCM Ministry Highlights — December 26, 2024",
    titleTe: "KCM మినిస్ట్రీ హైలైట్స్ — డిసెంబర్ 26, 2024",
    titleHi: "KCM सेवकाई हाइलाइट्स — 26 दिसंबर 2024",
    description: "Ministry highlights and blessings from Kingdom of Christ Ministries, December 26, 2024.",
    category: "Special Services",
    date: "December 26, 2024",
    embedUrl: "https://www.youtube.com/embed/6wVR2p6EvMI?si=VtYRSF6HW1_o6N2G",
    thumbnail: "https://i.ytimg.com/vi/6wVR2p6EvMI/hqdefault.jpg",
    siParam: "VtYRSF6HW1_o6N2G",
  },
  {
    id: "kcm-video-25",
    branchId: "cmrgwqhc30001fsk8mysbmp50",
    branchName: "Subhash Nagar",
    branchSlug: "subhash-nagar",
    videoId: "nV1pss0W0K4",
    title: "KCM Prayer & Worship — December 26, 2024",
    titleTe: "KCM ప్రార్థన & ఆరాధన — డిసెంబర్ 26, 2024",
    titleHi: "KCM प्रार्थना और आराधना — 26 दिसंबर 2024",
    description: "Powerful prayer and worship session at Kingdom of Christ Ministries, December 26, 2024.",
    category: "Worship & Praise",
    date: "December 26, 2024",
    embedUrl: "https://www.youtube.com/embed/nV1pss0W0K4?si=_NMwedTORa9jsDx2",
    thumbnail: "https://i.ytimg.com/vi/nV1pss0W0K4/hqdefault.jpg",
    siParam: "_NMwedTORa9jsDx2",
  },
  {
    id: "kcm-video-26",
    branchId: "cmrgwqhc30001fsk8mysbmp50",
    branchName: "Subhash Nagar",
    branchSlug: "subhash-nagar",
    videoId: "ZXwWy5IOPBQ",
    title: "KCM Special Dance Performance — December 26, 2024",
    titleTe: "KCM ప్రత్యేక నృత్య ప్రదర్శన — డిసెంబర్ 26, 2024",
    titleHi: "KCM विशेष नृत्य प्रदर्शन — 26 दिसंबर 2024",
    description: "A special dance performance at the Kingdom of Christ Ministries Christmas event, December 26, 2024.",
    category: "Youth & Children",
    date: "December 26, 2024",
    embedUrl: "https://www.youtube.com/embed/ZXwWy5IOPBQ?si=3dLZp1Q1sK4FBU99",
    thumbnail: "https://i.ytimg.com/vi/ZXwWy5IOPBQ/hqdefault.jpg",
    siParam: "3dLZp1Q1sK4FBU99",
  },
  {
    id: "kcm-video-27",
    branchId: "cmrgwqhc30001fsk8mysbmp50",
    branchName: "Subhash Nagar",
    branchSlug: "subhash-nagar",
    videoId: "k99CkoVA0QQ",
    title: "KCM Church Service — December 27, 2024",
    titleTe: "KCM చర్చి సేవ — డిసెంబర్ 27, 2024",
    titleHi: "KCM चर्च सेवा — 27 दिसंबर 2024",
    description: "Kingdom of Christ Ministries church service from December 27, 2024.",
    category: "Special Services",
    date: "December 27, 2024",
    embedUrl: "https://www.youtube.com/embed/k99CkoVA0QQ?si=uRJIolUFDM482VMs",
    thumbnail: "https://i.ytimg.com/vi/k99CkoVA0QQ/hqdefault.jpg",
    siParam: "uRJIolUFDM482VMs",
  },
  {
    id: "kcm-video-28",
    branchId: "cmrgwqhc30001fsk8mysbmp50",
    branchName: "Subhash Nagar",
    branchSlug: "subhash-nagar",
    videoId: "CK4Z-REUDug",
    title: "KCM Praise Night — December 27, 2024",
    titleTe: "KCM స్తుతి రాత్రి — డిసెంబర్ 27, 2024",
    titleHi: "KCM स्तुति रात्रि — 27 दिसंबर 2024",
    description: "A powerful praise night at Kingdom of Christ Ministries, December 27, 2024.",
    category: "Worship & Praise",
    date: "December 27, 2024",
    embedUrl: "https://www.youtube.com/embed/CK4Z-REUDug?si=pOZR5KdBVMhdxgAN",
    thumbnail: "https://i.ytimg.com/vi/CK4Z-REUDug/hqdefault.jpg",
    siParam: "pOZR5KdBVMhdxgAN",
  },
  {
    id: "kcm-video-29",
    branchId: "cmrgwqhc30001fsk8mysbmp50",
    branchName: "Subhash Nagar",
    branchSlug: "subhash-nagar",
    videoId: "Jhc4pDeswBg",
    title: "KCM Special Service — December 12, 2025",
    titleTe: "KCM ప్రత్యేక సేవ — డిసెంబర్ 12, 2025",
    titleHi: "KCM विशेष सेवा — 12 दिसंबर 2025",
    description: "Special church service and ministry moments at Kingdom of Christ Ministries, December 12, 2025.",
    category: "Special Services",
    date: "December 12, 2025",
    embedUrl: "https://www.youtube.com/embed/Jhc4pDeswBg?si=VjevPxVxTxQI8aHZ",
    thumbnail: "https://i.ytimg.com/vi/Jhc4pDeswBg/hqdefault.jpg",
    siParam: "VjevPxVxTxQI8aHZ",
  },
  {
    id: "kcm-video-30",
    branchId: "cmrgwqhc30001fsk8mysbmp50",
    branchName: "Subhash Nagar",
    branchSlug: "subhash-nagar",
    videoId: "EccnBhiLqcI",
    title: "KCM 2025 Christmas Celebration Dance",
    titleTe: "KCM 2025 క్రిస్మస్ వేడుక నృత్యం",
    titleHi: "KCM 2025 क्रिसमस उत्सव नृत्य",
    description: "Energetic Christmas celebration dance and praise at Kingdom of Christ Ministries, 2025.",
    category: "Christmas Events",
    date: "December 2025",
    embedUrl: "https://www.youtube.com/embed/EccnBhiLqcI?si=87GiCGY6-vNGBCFg",
    thumbnail: "https://i.ytimg.com/vi/EccnBhiLqcI/hqdefault.jpg",
    siParam: "87GiCGY6-vNGBCFg",
  },
  {
    id: "kcm-video-31",
    branchId: "cmrgwqhc30001fsk8mysbmp50",
    branchName: "Subhash Nagar",
    branchSlug: "subhash-nagar",
    videoId: "ZkePBVVN1eE",
    title: "KCM Ministry Service — December 12, 2025",
    titleTe: "KCM మినిస్ట్రీ సేవ — డిసెంబర్ 12, 2025",
    titleHi: "KCM सेवकाई सेवा — 12 दिसंबर 2025",
    description: "Ministry service and fellowship at Kingdom of Christ Ministries, December 12, 2025.",
    category: "Special Services",
    date: "December 12, 2025",
    embedUrl: "https://www.youtube.com/embed/ZkePBVVN1eE?si=j1JnbXx-nVch6VFk",
    thumbnail: "https://i.ytimg.com/vi/ZkePBVVN1eE/hqdefault.jpg",
    siParam: "j1JnbXx-nVch6VFk",
  },
  {
    id: "kcm-video-32",
    branchId: "cmrgwqhc30001fsk8mysbmp50",
    branchName: "Subhash Nagar",
    branchSlug: "subhash-nagar",
    videoId: "YttFfV1YQSE",
    title: "KCM Worship Session — December 12, 2025",
    titleTe: "KCM ఆరాధన సెషన్ — డిసెంబర్ 12, 2025",
    titleHi: "KCM आराधना सत्र — 12 दिसंबर 2025",
    description: "Worship session and praise at Kingdom of Christ Ministries, December 12, 2025.",
    category: "Worship & Praise",
    date: "December 12, 2025",
    embedUrl: "https://www.youtube.com/embed/YttFfV1YQSE?si=lOZRNf3hWTWAIyl7",
    thumbnail: "https://i.ytimg.com/vi/YttFfV1YQSE/hqdefault.jpg",
    siParam: "lOZRNf3hWTWAIyl7",
  },
  {
    id: "kcm-video-33",
    branchId: "cmrgwqhc30002fsk8ncn255w5",
    branchName: "Bahadurpalli",
    branchSlug: "bahadurpally",
    videoId: "oawi3vqbRJs",
    title: "KCM Christmas Gathering — December 17, 2025",
    titleTe: "KCM క్రిస్మస్ కూడిక — డిసెంబర్ 17, 2025",
    titleHi: "KCM क्रिसमस सभा — 17 दिसंबर 2025",
    description: "Christmas gathering and praise service at Kingdom of Christ Ministries, December 17, 2025.",
    category: "Christmas Events",
    date: "December 17, 2025",
    embedUrl: "https://www.youtube.com/embed/oawi3vqbRJs?si=VxaEp4875kQBsAB7",
    thumbnail: "https://i.ytimg.com/vi/oawi3vqbRJs/hqdefault.jpg",
    siParam: "VxaEp4875kQBsAB7",
  },
  {
    id: "kcm-video-34",
    branchId: "cmrgwqhc30002fsk8ncn255w5",
    branchName: "Bahadurpalli",
    branchSlug: "bahadurpally",
    videoId: "pGF2psYG49c",
    title: "KCM Children's Performance — December 17, 2025",
    titleTe: "KCM పిల్లల ప్రదర్శన — డిసెంబర్ 17, 2025",
    titleHi: "KCM बच्चों का प्रदर्शन — 17 दिसंबर 2025",
    description: "Adorable children's performance at Kingdom of Christ Ministries Christmas event, December 17, 2025.",
    category: "Youth & Children",
    date: "December 17, 2025",
    embedUrl: "https://www.youtube.com/embed/pGF2psYG49c?si=1T9j2RCXfFeOsHmg",
    thumbnail: "https://i.ytimg.com/vi/pGF2psYG49c/hqdefault.jpg",
    siParam: "1T9j2RCXfFeOsHmg",
  },
  {
    id: "kcm-video-35",
    branchId: "cmrgwqhc30002fsk8ncn255w5",
    branchName: "Bahadurpalli",
    branchSlug: "bahadurpally",
    videoId: "lFQiBQPedqE",
    title: "KCM Worship & Dance — December 17, 2025",
    titleTe: "KCM ఆరాధన & నృత్యం — డిసెంబర్ 17, 2025",
    titleHi: "KCM आराधना और नृत्य — 17 दिसंबर 2025",
    description: "Worship and dance performance at Kingdom of Christ Ministries, December 17, 2025.",
    category: "Worship & Praise",
    date: "December 17, 2025",
    embedUrl: "https://www.youtube.com/embed/lFQiBQPedqE?si=MDe92SFuiMCW6q61",
    thumbnail: "https://i.ytimg.com/vi/lFQiBQPedqE/hqdefault.jpg",
    siParam: "MDe92SFuiMCW6q61",
  },
  {
    id: "kcm-video-36",
    branchId: "cmrgwqhc30002fsk8ncn255w5",
    branchName: "Bahadurpalli",
    branchSlug: "bahadurpally",
    videoId: "KquomxWpi88",
    title: "KCM Youth Praise — December 17, 2025",
    titleTe: "KCM యువత స్తుతి — డిసెంబర్ 17, 2025",
    titleHi: "KCM युवा स्तुति — 17 दिसंबर 2025",
    description: "Youth praise and celebration at Kingdom of Christ Ministries, December 17, 2025.",
    category: "Youth & Children",
    date: "December 17, 2025",
    embedUrl: "https://www.youtube.com/embed/KquomxWpi88?si=cSttw6ItavURkIbm",
    thumbnail: "https://i.ytimg.com/vi/KquomxWpi88/hqdefault.jpg",
    siParam: "cSttw6ItavURkIbm",
  },
  {
    id: "kcm-video-37",
    branchId: "cmrgwqhc30002fsk8ncn255w5",
    branchName: "Bahadurpalli",
    branchSlug: "bahadurpally",
    videoId: "stQQQ2STFOk",
    title: "KCM Christmas Festival — December 26, 2025",
    titleTe: "KCM క్రిస్మస్ పండుగ — డిసెంబర్ 26, 2025",
    titleHi: "KCM क्रिसमस महोत्सव — 26 दिसंबर 2025",
    description: "Grand Christmas festival celebration at Kingdom of Christ Ministries, December 26, 2025.",
    category: "Christmas Events",
    date: "December 26, 2025",
    embedUrl: "https://www.youtube.com/embed/stQQQ2STFOk?si=tWGKv7CwN-CngUYT",
    thumbnail: "https://i.ytimg.com/vi/stQQQ2STFOk/hqdefault.jpg",
    siParam: "tWGKv7CwN-CngUYT",
  },
  {
    id: "kcm-video-38",
    branchId: "cmrgwqhc30002fsk8ncn255w5",
    branchName: "Bahadurpalli",
    branchSlug: "bahadurpally",
    videoId: "EXubhARc334",
    title: "KCM Revival Service — December 26, 2025",
    titleTe: "KCM పునరుజ్జీవన సేవ — డిసెంబర్ 26, 2025",
    titleHi: "KCM पुनरुत्थान सेवा — 26 दिसंबर 2025",
    description: "Powerful revival service and prayer at Kingdom of Christ Ministries, December 26, 2025.",
    category: "Revival & Blessings",
    date: "December 26, 2025",
    embedUrl: "https://www.youtube.com/embed/EXubhARc334?si=WIA8booueaGmibGv",
    thumbnail: "https://i.ytimg.com/vi/EXubhARc334/hqdefault.jpg",
    siParam: "WIA8booueaGmibGv",
  },
  {
    id: "kcm-video-39",
    branchId: "cmrgwqhc30002fsk8ncn255w5",
    branchName: "Bahadurpalli",
    branchSlug: "bahadurpally",
    videoId: "Fjp-x61a894",
    title: "KCM Blessing Gathering — December 26, 2025",
    titleTe: "KCM ఆశీర్వాద కూడిక — డిసెంబర్ 26, 2025",
    titleHi: "KCM आशीष सभा — 26 दिसंबर 2025",
    description: "Blessing gathering and corporate prayer at Kingdom of Christ Ministries, December 26, 2025.",
    category: "Revival & Blessings",
    date: "December 26, 2025",
    embedUrl: "https://www.youtube.com/embed/Fjp-x61a894?si=0zdiXsVInNpvoWn-",
    thumbnail: "https://i.ytimg.com/vi/Fjp-x61a894/hqdefault.jpg",
    siParam: "0zdiXsVInNpvoWn-",
  },
  {
    id: "kcm-video-40",
    branchId: "cmrgwqhc30002fsk8ncn255w5",
    branchName: "Bahadurpalli",
    branchSlug: "bahadurpally",
    videoId: "2Zrw6InPMFg",
    title: "KCM Praise & Fellowship — December 26, 2025",
    titleTe: "KCM స్తుతి & సహవాసం — డిసెంబర్ 26, 2025",
    titleHi: "KCM स्तुति और संगति — 26 दिसंबर 2025",
    description: "Joyful praise and fellowship moments at Kingdom of Christ Ministries, December 26, 2025.",
    category: "Worship & Praise",
    date: "December 26, 2025",
    embedUrl: "https://www.youtube.com/embed/2Zrw6InPMFg?si=-e5q5xJvFbmQEbb0",
    thumbnail: "https://i.ytimg.com/vi/2Zrw6InPMFg/hqdefault.jpg",
    siParam: "-e5q5xJvFbmQEbb0",
  },
  {
    id: "kcm-video-41",
    branchId: "cmrgwqhc30002fsk8ncn255w5",
    branchName: "Bahadurpalli",
    branchSlug: "bahadurpally",
    videoId: "Lz2JpmniW98",
    title: "KCM Ministry Dance — December 26, 2025",
    titleTe: "KCM మినిస్ట్రీ నృత్యం — డిసెంబర్ 26, 2025",
    titleHi: "KCM सेवकाई नृत्य — 26 दिसंबर 2025",
    description: "Ministry dance and celebration at Kingdom of Christ Ministries, December 26, 2025.",
    category: "Youth & Children",
    date: "December 26, 2025",
    embedUrl: "https://www.youtube.com/embed/Lz2JpmniW98?si=IlicM3s5rNt9XCJ1",
    thumbnail: "https://i.ytimg.com/vi/Lz2JpmniW98/hqdefault.jpg",
    siParam: "IlicM3s5rNt9XCJ1",
  },
  {
    id: "kcm-video-42",
    branchId: "cmrgwqhc30002fsk8ncn255w5",
    branchName: "Bahadurpalli",
    branchSlug: "bahadurpally",
    videoId: "WJ-3jOnQqZY",
    title: "KCM Christmas Worship — December 26, 2025",
    titleTe: "KCM క్రిస్మస్ ఆరాధన — డిసెంబర్ 26, 2025",
    titleHi: "KCM क्रिसमस आराधना — 26 दिसंबर 2025",
    description: "Christmas worship and congregational singing at Kingdom of Christ Ministries, December 26, 2025.",
    category: "Christmas Events",
    date: "December 26, 2025",
    embedUrl: "https://www.youtube.com/embed/WJ-3jOnQqZY?si=VtcsUzhpWgD8xRmv",
    thumbnail: "https://i.ytimg.com/vi/WJ-3jOnQqZY/hqdefault.jpg",
    siParam: "VtcsUzhpWgD8xRmv",
  },
  {
    id: "kcm-video-43",
    branchId: "cmrgwqhc30002fsk8ncn255w5",
    branchName: "Bahadurpalli",
    branchSlug: "bahadurpally",
    videoId: "FZE_ynHmIKU",
    title: "KCM Church Gathering — December 27, 2025",
    titleTe: "KCM చర్చి కూడిక — డిసెంబర్ 27, 2025",
    titleHi: "KCM कलीसिया सभा — 27 दिसंबर 2025",
    description: "Church gathering and prayer service at Kingdom of Christ Ministries, December 27, 2025.",
    category: "Special Services",
    date: "December 27, 2025",
    embedUrl: "https://www.youtube.com/embed/FZE_ynHmIKU?si=Z2f4iuSCBp8-Rk5f",
    thumbnail: "https://i.ytimg.com/vi/FZE_ynHmIKU/hqdefault.jpg",
    siParam: "Z2f4iuSCBp8-Rk5f",
  },
  {
    id: "kcm-video-44",
    branchId: "cmrgwqhc30002fsk8ncn255w5",
    branchName: "Bahadurpalli",
    branchSlug: "bahadurpally",
    videoId: "9u6JySW_tVU",
    title: "KCM Revival Night — December 27, 2025",
    titleTe: "KCM పునరుజ్జీవన రాత్రి — డిసెంబర్ 27, 2025",
    titleHi: "KCM पुनरुत्थान रात्रि — 27 दिसंबर 2025",
    description: "A powerful revival night and blessing service at Kingdom of Christ Ministries, December 27, 2025.",
    category: "Revival & Blessings",
    date: "December 27, 2025",
    embedUrl: "https://www.youtube.com/embed/9u6JySW_tVU?si=vdJTI3l5OwXWx0jC",
    thumbnail: "https://i.ytimg.com/vi/9u6JySW_tVU/hqdefault.jpg",
    siParam: "vdJTI3l5OwXWx0jC",
  },
];

export const VIDEO_CATEGORIES: { name: VideoCategory; label: string }[] = [
  { name: "All", label: "All Videos" },
  { name: "Revival & Blessings", label: "Revival & Blessings" },
  { name: "Christmas Events", label: "Christmas Events" },
  { name: "Worship & Praise", label: "Worship & Praise" },
  { name: "Youth & Children", label: "Youth & Children" },
  { name: "Special Services", label: "Special Services" },
];

export const CATEGORY_COLORS: Record<VideoCategory, string> = {
  "All": "purple",
  "Revival & Blessings": "amber",
  "Christmas Events": "rose",
  "Worship & Praise": "blue",
  "Youth & Children": "emerald",
  "Special Services": "indigo",
};

export function filterAndSearchVideos(
  items: GalleryVideoItem[],
  category: VideoCategory,
  query: string,
  language: "en" | "te" | "hi",
  branchId?: string | null
): GalleryVideoItem[] {
  return items.filter((item) => {
    if (branchId && branchId !== "all") {
      if (!isBranchMatch(item.branchId, item.branchName, branchId)) {
        return false;
      }
    }
    if (category !== "All" && item.category !== category) return false;
    if (query && query.trim()) {
      const q = query.toLowerCase();
      const title = language === "te" ? (item.titleTe || item.title) : language === "hi" ? (item.titleHi || item.title) : item.title;
      return (
        title.toLowerCase().includes(q) ||
        item.description.toLowerCase().includes(q) ||
        item.date.toLowerCase().includes(q) ||
        item.category.toLowerCase().includes(q) ||
        (item.branchName && item.branchName.toLowerCase().includes(q))
      );
    }
    return true;
  });
}
