apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kcm-kafka-servicemonitor
  namespace: messaging
  labels:
    app.kubernetes.io/name: kafka
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
  endpoints:
    - port: jmx
      interval: 15s
      scrapeTimeout: 10s
      path: /metrics
