apiVersion: v1
kind: Service
metadata:
  name: loki-gateway
  namespace: {{ .Values.namespace | default "logging" }}
  labels:
    app.kubernetes.io/name: loki-gateway
    app.kubernetes.io/component: logging
spec:
  type: ClusterIP
  ports:
    - port: 3100
      targetPort: 3100
      name: http-metrics
  selector:
    app.kubernetes.io/name: loki
