nameOverride: ""
fullnameOverride: ""

api:
  replicaCount: 2
  image:
    repository: ghcr.io/bunnyvalluri/kcm-backend
    tag: "7338c12804b41ea10e58926f8acd7381dc5e5e6f"
    pullPolicy: IfNotPresent
  port: 3001
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 8
    targetCPUUtilizationPercentage: 75

worker:
  enabled: true
  replicaCount: 1
  command: ["node", "worker.js"]
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

cron:
  enabled: true
  replicaCount: 1
  command: ["node", "cron.js"]
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

env:
  NODE_ENV: "production"
  PORT: "3001"
  REDIS_URL: "redis://:ref:redis-secret@kcm-redis:6379"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1001
